env:
  PILOT_ENABLE_ALPHA_GATEWAY_API: "true"
  PILOT_ENABLE_GATEWAY_API: "true"
  PILOT_ENABLE_GATEWAY_API_DEPLOYMENT_CONTROLLER: "true"
  PILOT_ENABLE_GATEWAY_API_STATUS: "true"

istiod:
  enableAnalysis: true

meshConfig:
  accessLogEncoding: JSON
  accessLogFile: /dev/stdout

global:
  logging:
    level: "default:debug"

  logAsJson: true
